Netherpad/Models/Document.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netherpad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public string Identifier { get; set; }
        public string Content { get; set; }
        public int Version { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}

Netherpad/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Netherpad.Controllers
{
	using Netherpad.Models;
	using Netherpad.Models.NetherpadWorkflows.CompletedWorkflows;
	using Netherpad.ViewModels;

	public class DocumentsController : Controller
    {
		private readonly NetherpadDataManager dataManager;

		public DocumentsController()
		{
			this.dataManager = new NetherpadDataManager(new NetherpadEntities());
		}

		public ActionResult Index()
        {
            return View();
        }

		public ActionResult Create(string name)
		{
			var document = new Document() { Name = name, Content = "", CreatedOn = DateTime.Now};
			var workflow = new CreateOrUpdateDocumentWorkflow(this.dataManager, document, string.Empty);
			var result = workflow.Execute();
			if (result.TotalSuccess)
			{
				return RedirectToAction("Edit", new { identifier = document.Identifier });
			}
			else
			{
				throw new Exception("hey there was a problem");
			}
		}

	    public ActionResult Edit(string identifier)
	    {
		    var document = this.dataManager.DocumentLocator.Find(identifier);
		    return View(new EditDocumentViewModel{Document = document, Versions = dataManager.DocumentLocator.FindPreviousVersions(document)});
	    }

		public ActionResult Save(string identifier, string content)
		{
			var document = this.dataManager.DocumentLocator.Find(identifier);
			var workflow = new CreateOrUpdateDocumentWorkflow(this.dataManager, document, content);
			var result = workflow.Execute();
			if (result.TotalSuccess)
			{
				return RedirectToAction("Edit", new { identifier = document.Identifier });
			}
			else
			{
				throw new Exception("hey there was a problem");
			}
		}
    }
}

Netherpad/Views/Documents/Edit.cshtml
@model Netherpad.ViewModels.EditDocumentViewModel

@{
	ViewBag.Title = @Model.Document.Name;
}


<div class="row">
	<div class="span9">
		<h2>@Model.Document.Name</h2>
		@using (Html.BeginForm("Save", "Documents", new { identifier = Model.Document.Identifier }))
		{
			@Html.TextArea("Content", Model.Document.Content, new {id="document_content", style="width: 100%; height: 300px;"})
			<p><input type="submit" value="Save Changed" /></p>
		}

		<h2>Preview</h2>

		@Model.Document.Content
	</div>
	<div class="span3">
		<h2>Versions</h2>
		<ul>
		@foreach (var version in @Model.Versions)
		{
			<li>@version.Version</li>
		}
		</ul>
	</div>
</div>


@section scripts
{
	@Scripts.Render("~/bundles/signalr")

	<script src="@Url.Content("~/signalr/hubs")" type="text/javascript"></script> 
	@Scripts.Render("~/bundles/share")
	
	<script>
		
		$(document).ready(function () {
			
		});
	</script>
		<script type="text/javascript">
			var session_name = '@Model.Document.Identifier';

			$(window).load(function () {
				// Obtain the server name from the current URL (we need this to construct the WebSocket URL)
				var server_name_match = /:\/\/([^\/]+)(?:\/|$)/.exec(document.location.href);
				if (server_name_match != null) {
					var server_name = server_name_match[1];
				} else {
					var server_name = "127.0.0.1:8080";
				}

				console.debug("Using WebSocket server", server_name, "and session name", session_name);

				var edit = document.getElementById("document_content");
				var collabEdit = new CollaborativeEditor(edit, "http://" + server_name + "/transport", session_name);

				if (window.WebSocket) {
					$("#websocket-notice").hide();
				}
			});
	</script>
}

Netherpad/Views/Documents/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home</h2>

@using (Html.BeginForm("Create", "Documents"))
{
	<p>Name: @Html.TextBox("Name")</p>
	<input type="submit" value="Create New Document" />
}